import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { twMerge } from "tailwind-merge";
import { SidebarItem } from "@/components/SidebarItem";
import { TbCircleNumber9Filled } from "react-icons/tb";
import { FaChartBar } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(`flex`, montserrat.className)}>
        <Sidebar>
          <SidebarItem>
            <FaChartBar size={26}/>
            <p className="ml-1">Dashboard</p>
          </SidebarItem>
          <SidebarItem>
            <TbCircleNumber9Filled size={26}/>
            <p className="ml-1">Subjects</p>
          </SidebarItem>
        </Sidebar>
        {children}
      </body>
    </html>
  );
}
